const funcOne = () => {
    try {
        console.log("Hello my name is Alex")
    } catch {
        console.log("In catch block")
    }
}